"""Digital-twin error experiment: the monitor is built from a PERTURBED structural
model (storey stiffness and floor mass errors), while the data are generated by the
unperturbed one.  The perturbed model supplies the sensitivities S, kappa, eta, the
damage cone, the nuisance projector and the null mean mu_0 used by the monitor.
"""
import contextlib
import numpy as np
import model as M
import monitors as MO


def perturbed_reference(rng, stiff_sd, mass_sd):
    n = M.N_STOREY
    ek = rng.normal(0.0, stiff_sd, n)
    em = rng.normal(0.0, mass_sd, n)
    Ks = M.KS * (1.0 + ek)[:, None, None]
    mass = M.M0 * (1.0 + em)
    s = 1.0 / np.sqrt(mass)
    A = Ks.sum(0) * s[:, None] * s[None, :]
    lam, Q = np.linalg.eigh(A)
    phi = Q * s[:, None]
    lam = lam[:M.N_MODES]; phi = phi[:, :M.N_MODES]
    S = np.zeros((M.N_MODES, n)); eta = np.zeros(M.N_MODES)
    for i in range(M.N_MODES):
        v = phi[:, i]
        den = (v @ (mass * v)) * lam[i]
        for j in range(n):
            S[i, j] = (v @ Ks[j] @ v) / den
        eta[i] = (v[M.LOADED_FLOORS] ** 2 * mass[M.LOADED_FLOORS]).sum() / (v @ (mass * v))
    return dict(S=S, kappa=S.sum(1), eta=eta, f0=np.sqrt(lam) / (2 * np.pi))


@contextlib.contextmanager
def patched_design(ref):
    """Temporarily replace the design quantities the monitor takes from the twin."""
    saved = dict(V=MO.V, SUPPORT=MO.SUPPORT, SUP_MAT=MO.SUP_MAT, P_PERP=MO.P_PERP,
                 VT=MO.VT, MU0=MO.MU0, LAMS=MO.LAMS,
                 kappa=M.REF['kappa'], eta=M.REF['eta'])
    try:
        Vn, supp = MO.cone_generators(ref['S'], MO.SIGMA_D)
        U = np.stack([ref['kappa'] / MO.SIGMA_D, ref['eta'] / MO.SIGMA_D], axis=1)
        Q, _ = np.linalg.qr(U)
        Pp = np.eye(len(MO.SIGMA_D)) - Q @ Q.T
        VTn = (Pp @ Vn.T).T
        nrm = np.linalg.norm(VTn, axis=1)
        VTn = VTn[nrm > 1e-8] / nrm[nrm > 1e-8, None]
        mu0, _ = MO.score_null_mean(Vn, MO.C_SCALE, n_mc=100_000)
        sup = np.zeros((Vn.shape[0], M.N_STOREY))
        for i, sd in enumerate(supp):
            for j, w in sd.items():
                sup[i, j] = w
        MO.V, MO.SUPPORT, MO.SUP_MAT, MO.P_PERP, MO.VT, MO.MU0 = Vn, supp, sup, Pp, VTn, mu0
        MO.LAMS = np.geomspace(0.05, 0.9 / mu0, MO.N_LAM)
        M.REF['kappa'], M.REF['eta'] = ref['kappa'], ref['eta']
        yield
    finally:
        MO.V, MO.SUPPORT, MO.SUP_MAT, MO.P_PERP = (saved['V'], saved['SUPPORT'],
                                                    saved['SUP_MAT'], saved['P_PERP'])
        MO.VT, MO.MU0, MO.LAMS = saved['VT'], saved['MU0'], saved['LAMS']
        M.REF['kappa'], M.REF['eta'] = saved['kappa'], saved['eta']
